### ISSUE TITLE
Make rotating screenshots larger

### ISSUE THREAD

**Issue by pavlos256** [OpenRA/OpenRAWeb#122]
The screenshots on the main page are tiny! They are actually 500x300 but scaled down.

Here's how it would look with larger screenshots and a new header font:
![oraweb](https://cloud.githubusercontent.com/assets/311595/3032808/48f50b4e-e05c-11e3-841a-ab66dbf95c4f.png)

**Comment by DreadKnight** [comment]
This would be indeed nicer :) Hope it gets implemented.

**Comment by pchote** [comment]
I'm moving forward with this now that #51 is finally resolved.
![](http://i.imgur.com/Adl0UnH.png)

**Comment by pchote** [comment]
Discussion in IRC surrounding this feature was that this is seen as unwanted duplication.  Too bad it wasn't done here in the years before I wasted time on implementing it...
