### ISSUE TITLE
Player statistics with country of origin

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRAWeb#197]
It would be nice to have statistics about where openra players are coming from at http://www.openra.net/players/.

**Comment by deniz1a** [comment]
And the page doesn't say which time zone is used for the hourly graph. Is it GMT?

**Comment by deniz1a** [comment]
And wouldn't it be better if the hover text over the graphs had both playing and waiting numbers shown at the same time?

**Comment by ihptru** [comment]
yes it's UTC

**Comment by Mailaender** [comment]
There is http://res0l.net/src/LiveORA/map.html but it seems pretty broken and unpolished.

**Comment by pchote** [comment]
Closing as reverse duplicate of #322.
