### ISSUE TITLE
Make openra.net (Google) mobile-friendly

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRAWeb#208]
Google is favoring MOBILE-FRIENDLY sites starting April 21st:
http://googlewebmastercentral.blogspot.fr/2015/04/rolling-out-mobile-friendly-update.html

Currently, our website doesn't pass the test:
https://www.google.com/webmasters/tools/mobile-friendly/?url=http%3A%2F%2Fopenra.net

The ranking of the website could be affected if it doesn't comply to these new rules.

**Comment by ihptru** [comment]
as design is not adaptive right now.

**Comment by x-a-n-a-x** [comment]
the website also fails the HTTP/2 test : https://tools.keycdn.com/http2-test

**Comment by x-a-n-a-x** [comment]
https://openrct2.website/ could be a good idea for a new layout for openra.net
- clean and simple layout
- appealing shellmap playing in the background
- passing the google mobile-friendly test : https://www.google.com/webmasters/tools/mobile-friendly/?url=https://openrct2.website/
- passing the HTTP2 test : https://tools.keycdn.com/http2-test
- the source code available: https://github.com/OpenRCT2/openrct2.github.io

**Comment by Mailaender** [comment]
https://openrct2.org/ is a static website with regular content like we have, but it is still mobile friendly. They are also integrating their forums way better, but that is another ticket. https://github.com/OpenRA/OpenRAWeb/issues/47

**Comment by x-a-n-a-x** [comment]
http://searchengineland.com/google-divide-index-giving-mobile-users-better-fresher-content-261037

**Comment by xan2622** [comment]
https://developers.google.com/web/tools/lighthouse/ can also be used to audit a website in Chrome.

**Comment by pchote** [comment]
This was resolved by the new site design in https://github.com/OpenRA/OpenRAWebsiteV3/
