### ISSUE TITLE
Player statistics data source is down

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRAWeb#211]
Not sure if this is temporary or forever. It looks like @xaionaro is not the owner of the domain http://openra.dxnet.net/ anymore. We could replace the rrdtool parsing with a whole new backend https://github.com/OpenRA/OpenRAMasterServer/issues/18 to avoid this in the future.

**Comment by obrakmann** [comment]
the stats have been removed for the time being in #212.
