### ISSUE TITLE
Server browser tooltips or explanations

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRAWeb#221]
The new server browser got better with the new check-boxes to filter games.

Plus it now features click-able links (IP addresses) to directly launch OpenRA and join the game.
I think it's not obvious at first sight that you can click on the IP (even if it's a link of course). It's not clear enough to understand that it can directly launch OpenRA (which is an awesome idea btw !).

I suggest to add two new DIVs with some explanations:

![serverbrowser](https://cloud.githubusercontent.com/assets/1732773/7793239/a405d9d6-02bc-11e5-8f22-f8b760b7296b.png)

This tooltip would only be displayed next to the first link of each column (for example, the first IP address shown in the first column). 

Creating a mouseover tooltip with CSS (appearing when the user hovers the link) could be enough but the problem would still be there : it would not be that obvious at first sight.

**Comment by x-a-n-a-x** [comment]
HTML code:
``` <a class="tooltips" href="#">CSS Tooltips<span>Click on the map name to see its details on the resource site</span></a> ```



Here is the CSS code for these DIVs:
```
a.tooltips {
  position: relative;
  display: inline;
}
a.tooltips span {
  position: absolute;
  width:140px;
  color: #FFFFFF;
  background: #000000;
  border: 2px solid #650B03;
  height: 82px;
  line-height: 82px;
  text-align: center;
  visibility: hidden;
  border-radius: 6px;
}
a.tooltips span:before {
  content: '';
  position: absolute;
  top: 50%;
  right: 100%;
  margin-top: -12px;
  width: 0; height: 0;
  border-right: 12px solid #650B03;
  border-top: 12px solid transparent;
  border-bottom: 12px solid transparent;
}
a.tooltips span:after {
  content: '';
  position: absolute;
  top: 50%;
  right: 100%;
  margin-top: -8px;
  width: 0; height: 0;
  border-right: 8px solid #000000;
  border-top: 8px solid transparent;
  border-bottom: 8px solid transparent;
}
a:hover.tooltips span {
  visibility: visible;
  opacity: 1;
  left: 100%;
  top: 50%;
  margin-top: -41px;
  margin-left: 15px;
  z-index: 999;
}
```

**Comment by pchote** [comment]
This has been superseded by the new site design https://github.com/OpenRA/OpenRAWebsiteV3/
