### ISSUE TITLE
Meta name="keywords"

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRAWeb#224]
Why doesn't the html code contain this line :

```<meta name="keywords" content="OpenRA, RTS, game engine, RTS game engine, strategy, mods, C&amp;C, Command and Conquer, C&amp;C95, C&quot;C1, C&amp;C95 Online, Online, LAN, multiplayer, Red Alert, Red, Alert, RA, RA1, RA95, Tiberian, Tiberian Dawn, TD, Dune, Dune 2000, Dune2000, D2K, Tiberium Sun, Tiberium, Sun, TS, Red Alert 2, RA2, Kane, GDI, Nod, The Brotherhood of Nod, The Global Defense Initiative, Atreides, Ordos, Harkonnen, Allies, Soviets, Westwood" />```

**Comment by Mailaender** [comment]
http://stackoverflow.com/questions/2167257/what-are-cons-to-not-to-use-meta-name-keywords-content-some-words

**Comment by x-a-n-a-x** [comment]
Even Youtube.com features them .. so I DO think this line matters.

**Comment by Mailaender** [comment]
It probably does not hurt so just file a pull request.
