### ISSUE TITLE
Add Steam group to community page.

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRAWeb#241]
http://steamcommunity.com/groups/openra4life/
is the most well maintained group and should be deemed the official group.

**Comment by Mailaender** [comment]
For the record: https://disqus.com/home/discussion/openra/release_20150614/#comment-2085213121 I decided against it. We don't have any control and don't publish anything there.

**Comment by Unit158** [comment]
I am actually a moderator of the new one and would like to maintain it, so I'm going to say that the discussion there is irrelevant.

**Comment by Unit158** [comment]
That discussion actually decided against http://steamcommunity.com/groups/openra/ being used.

**Comment by Unit158** [comment]
I'm currently talking to the current owner. Do you want to be owner of the group? I'd be happy to manage it otherwise.

**Comment by Mailaender** [comment]
I didn't know you had access there and assumed it would just rot like the previous group.

**Comment by Unit158** [comment]
Who can design the icons for this?

**Comment by Unit158** [comment]
Wrong button again *facepalm*

**Comment by pchote** [comment]
I made a svg steam icon as part of the aborted #281.
