### ISSUE TITLE
The <title></title> tag

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRAWeb#298]
We should really update our < title > < /title > tags. 

According to several SEO 2016 documentation pages that I read, the TITLE tag is still one of the most useful SEO techniques of 2016 (that and a mobile-friendly website https://github.com/OpenRA/OpenRAWeb/issues/208).

> Google typically displays the first 50-60 characters of a title tag, or as many characters as will fit into a 512-pixel display.

So, we still have room left to add more text.

Rationally, I suggest to add words like "Command and Conquer" and/or "strategy game(s)" into the TITLE tag.

**Comment by pchote** [comment]
Giant :-1: to polluting the user-visible page title with SEO crap.

**Comment by Mailaender** [comment]
According to [Google Analytics](https://analytics.google.com/analytics/web/#report/acquisition-channels/a48361645w79856055p82609916/%3Fexplorer-table.plotKeys%3D%5B%5D%26explorer-table.rowStart%3D0%26explorer-table.rowCount%3D100%26_r.drilldown%3Danalytics.trafficChannel%3AOrganic%20Search/) none of our visitors search for these terms or other generic descriptions. Everyone searches for "OpenRA" or "open ra" so I guess the title is already optimized in that regard.

**Comment by x-a-n-a-x** [comment]
Heh, this is exactly what the problem is : people should find "openra" in the results after searching for "Command and Conquer" or "red alert" but OpenRA.net isn't even on the first page of results after searching for these very common game titles. Big fail here. :-[

**Comment by Mailaender** [comment]
The first three "Command & Conquer Open Source" hits on @duckduckgo are already OpenRA links

![image](https://cloud.githubusercontent.com/assets/756669/16355057/09404e58-3aac-11e6-8579-16ee752a2e7e.png)

Remember. We already optimized the `<description>` in https://github.com/OpenRA/OpenRAWeb/pull/157.
