### ISSUE TITLE
Add download link for SteamOS users for latest package release

### ISSUE THREAD

**Issue by mdeguzis** [OpenRA/OpenRAWeb#321]
Per: https://github.com/OpenRA/OpenRA/issues/9201

As requested.

**Comment by Mailaender** [comment]
I found https://github.com/mdeguzis/SteamOS-Tools/issues/143 but it seems to be gone.

**Comment by mdeguzis** [comment]
@Mailaender  had to put new pkgs / repo on hold due to finances and SteamOS not yet on Debian Stretch (really). :)
