### ISSUE TITLE
Resolve Octokit::TooManyRequests once and for all

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRAWeb#324]
> Octokit::TooManyRequests: GET https://api.github.com/repos/OpenRA/OpenRA/releases/2280129: 403 - API rate limit exceeded for 52.0.240.122. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting

See https://github.com/OpenRA/OpenRAWeb/pull/253 for my failed attempts. Maybe caching the file sizes/links and doing the lookup only when necessary (final push prior to release) might already lessen the problem.

**Comment by pchote** [comment]
I am assuming that the rate limit is done per build slave / ip, not per project, based on the fact that restarting the build a few times will eventually succeed.  Reducing our lookups won't help if that is the case.

**Comment by Phrohdoh** [comment]
Indeed it is per-IP.
