### ISSUE TITLE
Links to packages not working / missing on download page.

### ISSUE THREAD

**Issue by docholiday** [OpenRA/OpenRAWeb#329]
Hi, as I try to install OpenRA on an offline PC, I wanted to download the ra packages separately.
On the download section I didn't find them, however I found this page:
http://www.openra.net/news/dns-issues/
 
But the links to the packages aren't working anymore. Would be really great if you could add them to your download section!

edit:
I downloaded the ISO files from cncnz.com however after the first 3 discs worked, the Aftermath-Disc is not recognized by the installer and the "C&C Desert Tileset" is missing as well, so I'm still stuck :-(

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRAWeb/tree/master/content/packages

**Comment by docholiday** [comment]
Thank you :-)

**Comment by docholiday** [comment]
Hmm, I downloaded the desert.mix and placed it in C:\Users\[my user]\Documents\OpenRA\Content\cnc\ according to this wiki page: https://github.com/OpenRA/OpenRA/wiki/Game-Content
(the folders existed already, only the cnc folder was missing).

As that didn't work, I also tried putting it in
C:\Users\[my user]\Documents\OpenRA\Content\ra\
and even
C:\Users\[my user]\Documents\OpenRA\Content\ra\v2\

But the installer still says, that it is missing...

**Comment by pchote** [comment]
So close! It needs to be in `C:\Users[my user]\Documents\OpenRA\Content\ra\v2\cnc`.

**Comment by docholiday** [comment]
Thanks a lot, that worked :-)
But you should change the wiki accordingly...

**Comment by Mailaender** [comment]
[Updated.](https://github.com/OpenRA/OpenRA/wiki/Game-Content/_compare/064e4b7a425ac991d66c576a509dc2820cf6f940...b14c16fcd86ecc9c671b5a1827545a0d4cd23052)

**Comment by abcdefg30** [comment]
We don't seem to use a `v2` directory for the `cnc` mod though.

**Comment by pchote** [comment]
Indeed we don't.

**Comment by Mailaender** [comment]
It wouldn't be an OpenRA standard if it would be consistent with the TD mod.

**Comment by pchote** [comment]
Indeed... as usual this was because TD had learned from the mistakes of the RA mod and set up the assets properly so that we haven't need to make breaking compatibility changes.

**Comment by pchote** [comment]
Closing, as the original issue has been resolved.
