### ISSUE TITLE
Forum spam

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRAWeb#362]
is a problem and the manual cleanup costs valueable time:

![image](https://user-images.githubusercontent.com/756669/32430393-67e5e646-c2cf-11e7-927c-304853a8caf4.png)

A proper anti-spam solution probably depends on https://github.com/OpenRA/OpenRAWeb/issues/48.

**Comment by pchote** [comment]
The forum has a custom anti-spam which works well, with typically only 2 or 3 spam posts a month.  You just happened to look at the one and only time in the last couple of years where a human from a residential USA ISP registered accounts to spam.  There is no technical defense against that.
