### ISSUE TITLE
Dark red text on black background is hard to read

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRAWeb#363]
On my screen, the red text on http://www.openra.net/about/ doesn't have enough contrast.

**Comment by pchote** [comment]
Would you mind trying out different shades and testing an alternative?

**Comment by pchote** [comment]
How about the `#FFFF56` highlight from the stitching in the "Fork Me" badge?

![](https://screenshots.firefoxusercontent.com/images/6cd8784b-4158-4063-8074-b373ef929c04.png)

**Comment by glen7** [comment]
I disagree. The white transparency behind compensates for any lack of contrast, and I don't see a lack of contrast anyways.

**Comment by anjew175** [comment]
I have provided a couple of mock ups, as suggested, to see which is the most fitting
[https://imgur.com/a/0rwF71z](url)
I much prefer the #ffc100 to the #FFFF56 as it is a less vivid yellow that is a bit easier on the eyes
I have provided #ff0000 as an example of a non-dark red (pure red), I don't mind the colour but it is just as intense on the eyes as #FFF56.
