### ISSUE TITLE
Implement authentication backend as a phpBB3 extension.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRAWeb#381]
The custom Sleipnir's Stuff backend should be ported to the phpBB3 extension format and enabled on the main forum.  The forum privacy policy already includes a section on the account linking, so we can switch it on as soon as it is ready. I can share the original php code on request if someone else is able to help implement this.

References:
* https://github.com/OpenRA/OpenRA/issues/2265
* https://www.phpbb.com/extensions/

**Comment by pchote** [comment]
Screenshots from the original implementation:

![screen shot 2018-05-29 at 21 26 46](https://user-images.githubusercontent.com/167819/40684701-f45229ae-6389-11e8-8192-90610e89c57e.png)
![screen shot 2018-05-29 at 21 46 35](https://user-images.githubusercontent.com/167819/40684703-f707d3ce-6389-11e8-99ef-f6ac7511b089.png)

**Comment by Papi94** [comment]
Pchote, i think it's best we develop a user management and leader board system standalone, rather than use phpbb.

I'd take on the web interface and web api if someone else wants to implement it in to the game.

**Comment by lawando** [comment]
IMO it makes sense to utilize the existing code and implement the authentication into the new forums. This has been delayed for a long time already. Global leaderboards per mod would be nice but seem not maintainable atm. The proposed system (generating keys ingame and pasting them in the user control panel) isn't perfect as it requires manual steps but it gets the job done. Utilizing forum accounts has also the advantage that users do not have to manage multiple accounts.

**Comment by lawando** [comment]
Just for reference, the relevant part of the phpbb3 documentation about adding UCP modules via a custom extension can be found can be found [here ](https://area51.phpbb.com/docs/dev/3.2.x/extensions/tutorial_modules.html#)and there is another version [here](https://wiki.phpbb.com/Creating_modules).

**Comment by pchote** [comment]
We will provide the authentication API integrated in OpenRA, but it will be up to the community / server operators to develop and maintain their own leaderboards.  It would be impossible for us to maintain a global leaderboard system that works for all servers and all OpenRA mods (including all custom mods too).   It is simply too open ended (how do we present a players stats across 20 or 30 different games?) and would have huge moderation overheads to ensure that people weren't outright cheating.

**Comment by lawando** [comment]
WIP extension is available https://github.com/lawando/ORAuthenticator. It interacts with the db but essential parts of the front end are still missing.

**Comment by matjaeck** [comment]
Can be closed now that OpenRA/OpenRA#15333 got merged and the OpenRA/openrauseraccounts phpBB back-end is online.
