### ISSUE TITLE
Integrate pages as custom phpbb page templates

### ISSUE THREAD

**Issue by lawando** [OpenRA/OpenRAWeb#384]
The forum software is capable of managing custom pages and allows to use phpbb template parts and functions within them. Adding custom page templates would allow to use one backend for the whole website, post release information in an embedded "Release news" category and use the forum for comments on any of these embedded threads instead of the disqus plugin. It would also allow to use a global header/footer for all pages and logging in from the homepage. Content of other pages like "About" or "Downloads" could be managed via an extension that adds input fields to a custom admin control panel which are then used in custom page templates. 

The custom page templates depend on the outcome of #47 and if we manage to integrate a frontend framework, which would make a lot of sense for this.

Edit: I haven't thought of compatibility with github pages and that we want to generate static pages from the repo. PHP templates won't work with this, unfortunately.

References: 
- [Tutorial Adding pages](https://wiki.phpbb.com/Tutorial.Adding_pages)
- [Add a New Custom About Page to phpBB](https://www.phpbb.com/support/docs/en/3.1/kb/article/add-a-new-custom-page-to-phpbb/)
- [Another way to do it](https://www.thehelper.net/threads/phpbb3-custom-front-page.90623/)
- [External login](https://wiki.phpbb.com/Practical.External_login)

Edit
- There is also an [official pages extension](https://www.phpbb.com/customise/db/extension/pages/) but it seems to overcomplicate things imo.

**Comment by pchote** [comment]
This would mean moving the main website back onto our own infrastructure, which would be a very bad idea.  Back in the old days we had to panic whenever OpenRA was posted on Reddit or other popular sites because the resulting surge in traffic would cripple the server and take everything offline.  Hosting the site on GitHub pages solves this, and ensures a fast and smooth experience for visitors as it is hosted from a worldwide CDN.

**Comment by lawando** [comment]
Integration is indeed a bad idea, nevertheless a common design for forum and statically generated site would be worthwhile. The proper way to do it is probably to make sure the new theme's template markup for common elements like header/navigation/footer are re-usable for a refactoring of the static site in a subsequent step.
