### ISSUE TITLE
Create a new OpenRAForum project

### ISSUE THREAD

**Issue by lawando** [OpenRA/OpenRAWeb#385]
The updated forum software opens the opportunity to contribute to the now official OpenRA forum with  custom extensions and themes. While #46 shows the close relation of the static and dynamic parts of the site, issues like #47, #352 and #381 are explicitly aimed at the (phpbb) forum software. To promote contributions and provide information about development of (phpbb) extensions and themes, it would make sense to separate the static and dynamic parts on repository level. 

Another reason to separate things is that phpbb and atleast all extensions based on the skeleton are licensed under GPLv2-only. Having a GPLv2-only environment for related software avoids all OpenRAWeb license-related questions.

A repository with the current forum software being phpbb could look like this:
```
root
   /docs 
     coding-guidelines.html*
     events.md*
     vagrant.md*
      ...*

   /ext
      /OpenRAForum
         /<custom_extension>

   /styles
      /<custom_theme>
README.md
LICENCE

*files copied from phpbb installation. 
```
<sup>The official [skeleton ](https://www.phpbb.com/customise/db/official_tool/ext_skeleton/) extension would be linked somewhere. If extensions are based on the skeleton, setting the "Vendor" to `/OpenRAForum` will set up the extension's namespaces, filenames and structure automatically to fit the proposed structure . Otherwise `"name"` in `composer.json` would have to be set to `OpenRA/<custom_extension>` manually. </sup>

The original phpbb installation could then either track `/ext/OpenRAForum` and `/styles` or `root` while ignoring all local and remote root level files and folders except `/ext/OpenRAForum` and `/styles`.

**Comment by pchote** [comment]
The authentication extension and custom theme will want to have their own separate repositories, and issues against those can be field in their respective places.  IMO it is reasonable to keep any other general issues in this repository rather than to create a dummy repository.

**Comment by lawando** [comment]
> The authentication extension and custom theme will want to have their own separate repositories

That's probably the better idea the more I think about it. I assumed it was planned to use OpenRAWeb branches for them. Closing as it supersedes the point of the issue.
