### ISSUE TITLE
Forum, Badges, ability to give yourself any badge

### ISSUE THREAD

**Issue by SEAL-team-ricks** [OpenRA/OpenRAWeb#396]
I have found a bug on the forum related to the new feature of badges which allows anyone to give themselves any badge. 

to Replicate. 

[details omitted]

I have given myself OpenRA Developer as a badge. 

i've tried this with a couple.

**Comment by pchote** [comment]
Thanks for the report! And oops... this is pretty bad.

Ping @matjaeck - need to fix this ASAP.

For the record the repository for the authentication is https://github.com/OpenRA/openrauseraccounts but we'll be fixing this one soon enough that its not worth closing/refiling.

**Comment by SEAL-team-ricks** [comment]
to add i have verified this shows in game as well

**Comment by SEAL-team-ricks** [comment]
@pchote if you need help with this i'm a PHP dev by trade, I assume you guys have the resource to get it fixed quickly however

**Comment by pchote** [comment]
@SEAL-team-ricks: we should be able to fix this specific issue fast enough, but in general we have very little in the way of web-dev resources (@matjaeck learned php for/with this project, and I haven't had time to review the code in full detail).  If you are up to helping out, we'd really appreciate it if you could take a look through the linked repository and report any other security issues or bugs that you find!

**Comment by SEAL-team-ricks** [comment]
will PM you later @pchote
