### ISSUE TITLE
The Windows download page only lists the x64 build.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRAWeb#455]

**Comment by pchote** [comment]
The macOS and Linux pages also mention deps that are no longer required.

This is intentional, because the instructions are targeted for the current release. The platform-specific copy around the download buttons will be updated when the final release is deployed.

**Comment by pchote** [comment]
This has been resolved in the new site design https://github.com/OpenRA/OpenRAWebsiteV3/
