### ISSUE TITLE
OpenRA - DNS Issue web page download link doesn't work

### ISSUE THREAD

**Issue by pagyo** [OpenRA/OpenRAWeb#499]
![image](https://user-images.githubusercontent.com/8748617/100518185-55d4e780-3190-11eb-85ad-43a06e696e82.png)

**Comment by abcdefg30** [comment]
That article is really old, and I'm not sure if it is worth fixing. (Since https://www.openra.net/download/ works anyway.)

**Comment by pchote** [comment]
This has been resolved (by removing the links) in the new site design https://www.openra.net/news/dns-issues/
